services:
  webapp:
    container_name: webapp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=init
      - MYSQL_DATABASE=dental
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - myapp-network

  mysql:
    container_name: mysql
    image: mysql:8.3.0
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=init
      - MYSQL_DATABASE=dental
    volumes:
      - mysql-data:/var/lib/mysql
      # Mount the SQL scripts into the initialization directory
      - ./src/main/resources/ddl.sql:/docker-entrypoint-initdb.d/01-ddl.sql
      - ./src/main/resources/dml.sql:/docker-entrypoint-initdb.d/02-dml.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 15s
    networks:
      - myapp-network
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql-data:

networks:
  myapp-network:
    driver: bridge